name: Heroku Deploy
on:
  push:
    branches:
      - 'main'
      - 'heroku-setup'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # fetch complete commit history on all branches
          fetch-depth: 0
      # to configure secrets on github repo visit the following link
      # https://github.com/AkhileshNS/heroku-deploy
      - name: Set Heroku Credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY 
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku Remote
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku heroku-deploy:refs/heads/main
